server:
  port: 8080
spring:
  application:
    name: Mockito
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/mockito
    username: samuel
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC